<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ __('Customers') }} - {{ $business->name }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            color: #1a1a1a;
            line-height: 1.5;
            margin: 40px;
        }
        h1 {
            font-size: 24px;
            margin-bottom: 4px;
        }
        .subtitle {
            color: #6b7280;
            margin-bottom: 24px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th {
            background: #f3f4f6;
            text-align: left;
            padding: 10px 12px;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: #6b7280;
            border-bottom: 2px solid #e5e7eb;
        }
        td {
            padding: 10px 12px;
            border-bottom: 1px solid #e5e7eb;
        }
        .footer {
            margin-top: 32px;
            font-size: 10px;
            color: #9ca3af;
            text-align: center;
        }
    </style>
</head>
<body>
    <h1>{{ __('Customers') }}</h1>
    <div class="subtitle">{{ $business->name }} &mdash; {{ now()->format('F j, Y') }}</div>

    <table>
        <thead>
            <tr>
                <th>{{ __('Name') }}</th>
                <th>{{ __('Email') }}</th>
                <th>{{ __('Address') }}</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($customers as $customer)
                <tr>
                    <td>{{ $customer->name }}</td>
                    <td>{{ $customer->email ?? '—' }}</td>
                    <td>{{ $customer->address ?? '—' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="3" style="text-align: center; padding: 40px; color: #9ca3af;">
                        {{ __('No customers found.') }}
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        {{ __('Generated by :app on :date', ['app' => config('app.name'), 'date' => now()->format('Y-m-d H:i:s')]) }}
    </div>
</body>
</html>
